// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShopWebApi.Data.EntityFramework;

namespace ShopWebApi.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20210619042004_FinalMigrations")]
    partial class FinalMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ShopWebApi.Model.Entity.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ProductInformation")
                        .HasColumnType("text")
                        .HasColumnName("product_information");

                    b.Property<string>("ProductName")
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.HasKey("Id");

                    b.ToTable("products");
                });

            modelBuilder.Entity("ShopWebApi.Model.Entity.Reserve", b =>
                {
                    b.Property<Guid>("IdOrder")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("ReservationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reservation_time");

                    b.Property<Guid?>("product_id")
                        .HasColumnType("uuid");

                    b.HasKey("IdOrder");

                    b.HasIndex("product_id");

                    b.ToTable("reserved");
                });

            modelBuilder.Entity("ShopWebApi.Model.Entity.Warehouse", b =>
                {
                    b.Property<Guid>("Article")
                        .HasColumnType("uuid")
                        .HasColumnName("article");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("product_id")
                        .HasColumnType("uuid");

                    b.HasKey("Article");

                    b.HasIndex("product_id");

                    b.ToTable("warehouse");
                });

            modelBuilder.Entity("ShopWebApi.Model.Entity.Reserve", b =>
                {
                    b.HasOne("ShopWebApi.Model.Entity.Product", "Product")
                        .WithMany("Reserve")
                        .HasForeignKey("product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShopWebApi.Model.Entity.Warehouse", b =>
                {
                    b.HasOne("ShopWebApi.Model.Entity.Product", "Product")
                        .WithMany("Warehouse")
                        .HasForeignKey("product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShopWebApi.Model.Entity.Product", b =>
                {
                    b.Navigation("Reserve");

                    b.Navigation("Warehouse");
                });
#pragma warning restore 612, 618
        }
    }
}
